closes DSMCPTEAM-3007
Fiserv/global-currency-solutions pull request #85
Opened 2024-08-15 21:15 UTC by JJayachandra

2024-08-16 01:44 UTC, VinitSingh01 requested changes

2024-08-16 01:44 UTC, VinitSingh01 commented on reference/1.0.0/fx-rates.yaml
> +                $ref: '#/components/schemas/BadRequest'
It's not correct.

2024-08-17 01:16 UTC, JJayachandra commented
@VinitSingh01  please review, I have taken care of the review comment.

2024-08-20 15:38 UTC, VinitSingh01 approved these changes
approved

2024-08-20 15:38 UTC, merged